server:
  port: 8080

# 添加配置文件路径
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/LX1993728/spring-cloud-config-repo
          search-paths:
            - foo  # 仓库中/foo 路径下寻找
            - bar  # 仓库中/bar路径