server:
  port: 8080

# 私有仓库需要配置用户名和密码
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/LX1993728/spring-cloud-config-repo
          username: <私有仓库的用户名>
          password: <私有仓库的密码>