server:
  port: 8080

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/LX1993728/spring-cloud-config-repo
          repos:
            simple: https://github.com/LX1993728/simple
            special:
              pattern:
                - special/dev
                - special/test
              uri: https://github.com/LX1993728/special