spring:
  application:
    name: microservice-sidecar

server:
  port: 8070

eureka:
  client:
    service-url:
      defaultZone: http://liuxun:123456@localhost:8761/eureka
  instance:
    prefer-ip-address: true

sidecar:
  port: 8060
  health-uri: http://localhost:8060/health.json