server:
  port: 8080

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/LX1993728/spring-cloud-config-repo
encrypt:
  key-store:
    location: classpath:/server.jks
    password: 123456
    alias:  liuxun_alias
    secret: 123456

