server:
  port: 8080

# 认证配置
security:
  basic:
    enabled: true
  user:
    name: liuxun
    password: 123456


spring:
  cloud:
    config:
      server:
        git: #Git 远程配置仓库
          uri: https://github.com/LX1993728/spring-cloud-config-repo
  application:
    name: microservice-config-server
  rabbitmq:  #消息总线bus的消息中间件配置
    host: localhost
    port: 5672
    username: guest
    password: guest

encrypt:
  key-store: #配置非对称加密
    location: classpath:/server.jks
    password: 123456
    alias:  liuxun_alias
    secret: 123456
  key: foo  #配置对称加密的key

# 注册到Eureka服务注册中心
eureka:
  client:
    service-url:
      defaultZone: http://liuxun:123456@localhost:8761/eureka
  instance:
    prefer-ip-address: true