spring:
  application:
    name: microservice-gateway-zuul

server:
  port: 8040

eureka:
  client:
    service-url:
      defaultZone: http://liuxun:123456@localhost:8761/eureka
  instance:
    prefer-ip-address: true

zuul:
  ignoredPatterns: /**/simple/** #所有符合此格式的url都不会进行路由映射。
  routes:
    microservice-provider-user: /users/**
    microservice-consumer-movie-ribbon-with-hystrix: /consumer/**