spring:
  application:
    name: microservice-gateway-zuul

server:
  port: 8040

eureka:
  client:
    service-url:
      defaultZone: http://liuxun:123456@localhost:8761/eureka
  instance:
    prefer-ip-address: true

# 配置大文件上傳時，需要添加此配置 訪問時為/zuul/<route>/<uploadPath>
hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 60000
ribbon:
  ConnectTimeout: 3000
  ReadTimeout: 60000