spring:
  application:
    name: microservice-gateway-zuul

server:
  port: 8040

eureka:
  client:
    service-url:
      defaultZone: http://liuxun:123456@localhost:8761/eureka
  instance:
    prefer-ip-address: true
zuul:
  routes:
    ABC:
      path: /user-path/**
      serviceId: microservice-provider-user
