
security:
  basic:
    enabled: true
  user:
    name: liuxun
    password: 123456

server:
  port: 8080

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/LX1993728/spring-cloud-config-repo
