server:
  port: 8050
spring:
  application:
    name: microservice-file-upload
  http:
    multipart:
      max-file-size: 2000Mb    # Max file size,默认是1M
      max-request-size: 2500Mb # Max request size,默认是10M
eureka:
  client:
    service-url:
      defaultZone: http://liuxun:123456@localhost:8761/eureka # 声明注册中心地址
  instance:
    prefer-ip-address: true #显示IP地址
    instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}} #自定义在注册中心的显示格式，不是必须的
