security:
  basic:
    enabled: true
  user:
    name: liuxun
    password: 123456
spring:
  application:
    name: microservice-discovery-eureka-ha
---
server:
  port: 8761
spring:
  profiles: peer1
eureka:
  instance:
    hostname: peer1
  client:
#    register-with-eureka: false #防止将自身当做Eureka客户端
#    fetch-registry: false       #防止将自身当做Eureka客户端
    service-url:
      defaultZone: http://liuxun:123456@peer2:8762/eureka,http://liuxun:123456@peer3:8763/eureka
---
server:
  port: 8762
spring:
  profiles: peer2
eureka:
  instance:
    hostname: peer2
  client:
#    register-with-eureka: false #防止将自身当做Eureka客户端
#    fetch-registry: false       #防止将自身当做Eureka客户端
    service-url:
      defaultZone: http://liuxun:123456@peer1:8761/eureka,http://liuxun:123456@peer3:8763/eureka
---
server:
  port: 8763
spring:
  profiles: peer3
eureka:
  instance:
    hostname: peer3
  client:
#    register-with-eureka: false #防止将自身当做Eureka客户端
#    fetch-registry: false       #防止将自身当做Eureka客户端
    service-url:
      defaultZone: http://liuxun:123456@peer1:8761/eureka,http://liuxun:123456@peer2:8762/eureka
---