server:
  port: 8031

spring:
  application:
    name: microservice-hystrix-turbine3
eureka:
  client:
    service-url:
      defaultZone: http://liuxun:123456@localhost:8761/eureka # 声明注册中心地址
  instance:
    prefer-ip-address: true #显示IP地址
turbine:
  aggregator:
    clusterConfig: ABC
  appConfig: microservice-consumer-movie-ribbon-with-hystrix3
  cluster-name-expression: metadata['cluster']

logging:
  level:
    root: info
    com.netflix.trubine.monitor: debug
