server:
  port: 8080

# 配置自身的认证信息
security:
  basic:
    enabled: true
  user:
    name: liuxun
    password: 123456

# 从远程仓库获取配置
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/LX1993728/spring-cloud-config-repo
  application:
    name: microservice-config-server-eureka

# 注册到Eureka
eureka:
  client:
    service-url:
      defaultZone: http://liuxun:123456@localhost:8761/eureka
  instance:
    prefer-ip-address: true